library(comat)
library(stars)
library(dplyr)
library(rcartocolor)
library(sf)
landcover = read_stars(system.file("raster/landcover2015.tif", package = "motif"))
# plot(landcover)
lc_cove = lop_thumbprint(landcover, type = "cove", window_size = 100, normalization = "pdf")
lc_dist = lop_to_dist(lc_cove, dist_fun = "jensen-shannon")
lc_hclust = hclust(lc_dist, method = "ward.D2")
lc_cove$clust = cutree(lc_hclust, k = 12)

lc_grid = lop_add_spatial(lc_cove)
plot(lc_grid["clust"], col = carto_pal(12, "Safe"))
