---
title: "Signatures"
author: "Jakub Nowosad"
date: "`r Sys.Date()`"
output: 
  html_document:
  github_document:
    html_preview: true
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 7
)
```


```{r}
library(motif)
library(stars)
library(sf)
```


```{r}
landcover = read_stars(system.file("raster/landcover2015.tif", package = "motif"))
```

```{r}
landcover = droplevels(landcover)
plot(landcover, key.pos = 4, key.width = lcm(5), main = NULL)
```

```{r}
landform = read_stars(system.file("raster/landform.tif", package = "motif"))
```

```{r}
landform = droplevels(landform)
plot(landform, key.pos = 4, key.width = lcm(5), main = NULL)
```

```{r}
set.seed(222)
random_ndvi = landcover
random_ndvi$ndvi = sample(x = 1:10, size = length(random_ndvi[[1]]), replace = TRUE)
random_ndvi$ndvi[is.na(random_ndvi$landcover2015.tif)] = NA
random_ndvi$landcover2015.tif = NULL
```

```{r}
plot(random_ndvi)
```

## `"coma"` - one layer

```{r}
lsp_thumbprint(landcover, type = "coma", window = 100, threshold = 0.9)
```


```{r}
lsp_thumbprint(landcover, type = "cove", window = 100, threshold = 0.9)
```


## `"wecoma"` - two layers

```{r}
lsp_thumbprint(c(landcover, random_ndvi), type = "wecoma", threshold = 0.9)
```

```{r}
lsp_thumbprint(c(landcover, random_ndvi), type = "wecove", threshold = 0.9)
```


## `"incoma"` - two or more layers

```{r}
lsp_thumbprint(c(landcover, landform), type = "incoma",
               window = 100, threshold = 0.9)
```

```{r}
lsp_thumbprint(c(landcover, landform), type = "incove", 
               window = 100, threshold = 0.9)
```

## `"composition"` - one layer

```{r}
lsp_thumbprint(landcover, type = "composition",
               window = 100, threshold = 0.9)
```

## User-defined functions - one or more layers

```{r, eval=FALSE}
lsp_thumbprint(landcover, type = "composition",
               window = 100, threshold = 0.9)
```

```{r, eval=FALSE}
lsp_thumbprint(landcover, type = "composition",
               window = 100, threshold = 0.9)
```
