# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_attributes <- function(x) {
    .Call(`_lopata_create_attributes`, x)
}

get_motifel_size <- function(num_r, num_c, shift) {
    .Call(`_lopata_get_motifel_size`, num_r, num_c, shift)
}

get_motifels_cocoma <- function(x, y, directions, size, shift, threshold) {
    .Call(`_lopata_get_motifels_cocoma`, x, y, directions, size, shift, threshold)
}

get_motifels_coma <- function(x, directions, size, shift, threshold) {
    .Call(`_lopata_get_motifels_coma`, x, directions, size, shift, threshold)
}

get_motifels_incoma <- function(input, directions, size, shift, threshold) {
    .Call(`_lopata_get_motifels_incoma`, input, directions, size, shift, threshold)
}

get_motifels_wecoma <- function(x, w, directions, size, shift, threshold, fun, na_action) {
    .Call(`_lopata_get_motifels_wecoma`, x, w, directions, size, shift, threshold, fun, na_action)
}

get_mask_coma <- function(x, m) {
    .Call(`_lopata_get_mask_coma`, x, m)
}

matrix_locs <- function(M, locs) {
    .Call(`_lopata_matrix_locs`, M, locs)
}

na_prop <- function(x) {
    .Call(`_lopata_na_prop`, x)
}

